/*
 * esp32_tinyml_ids.ino
 * ---------------------
 * HARDWARE edge-detection node (real ESP32).
 *
 *   raw flow features -> StandardScaler -> PCA -> DecisionTree
 *       -> ESP32 edge inference -> Intrusion Alert -> Communication Layer
 *          (HTTP POST) -> Ryu SDN controller
 *
 * The scaler+PCA+tree are ALL embedded as plain C in generated_model.h
 * (auto-generated by `python3 -m ml.train_export`, see that file's
 * docstring) -- this is the SAME model used by the "software" edge
 * simulator (scripts/simulate_edge_node.py) when you don't have a
 * physical ESP32. Both produce identical predictions for identical
 * input, since they wrap the exact same fitted scaler/pca/tree.
 *
 * HARDWARE / LIBRARIES
 *   Board:      ESP32 Dev Module (Arduino-ESP32 core)
 *   Libraries:  WiFi.h, HTTPClient.h  (both ship with the ESP32 board
 *               package -- no extra installs needed)
 *
 * WHERE TO STORE
 *   esp32/esp32_tinyml_ids.ino   (this file)
 *   esp32/generated_model.h      (auto-generated -- must be in the
 *                                 SAME folder; Arduino IDE only looks
 *                                 inside the sketch folder)
 *
 * HOW TO RUN (hardware path)
 *   1. Install Arduino IDE 2.x, then Boards Manager -> "esp32 by
 *      Espressif Systems".
 *   2. Open esp32/esp32_tinyml_ids.ino (the esp32/ folder is the
 *      sketch; generated_model.h shows as a second tab automatically).
 *   3. Edit WIFI_SSID / WIFI_PASSWORD / CONTROLLER_URL below to match
 *      config.json (see "controller.alert_url" and "edge_node.wifi_*"
 *      -- the ESP32 cannot read the JSON file, so these must be copied
 *      in by hand).
 *   4. Tools -> Board -> ESP32 Dev Module, pick the COM port, Upload.
 *   5. Serial Monitor at 115200 baud to watch predictions/alerts.
 */

#include <WiFi.h>
#include <HTTPClient.h>
#include "generated_model.h"

// ---------- CONFIGURE THESE (mirror config.json) ----------
const char* WIFI_SSID     = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";
const char* CONTROLLER_URL = "http://192.168.1.10:8080/api/alert";
const char* DEVICE_ID       = "edge-sensor-01";
// ------------------------------------------------------------

const unsigned long SAMPLE_INTERVAL_MS = 2000;  // one classification every 2s
unsigned long lastSampleTime = 0;

void connectWiFi() {
  Serial.print("[WiFi] Connecting to ");
  Serial.println(WIFI_SSID);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println();
  Serial.print("[WiFi] Connected, IP = ");
  Serial.println(WiFi.localIP());
}

/*
 * getRawFeatureVector()
 * -----------------------
 * MUST return NUM_RAW_FEATURES floats, in the exact order of
 * RAW_FEATURE_NAMES (see generated_model.h / outputs/model_metadata.json).
 *
 * Two sources are supported in this reference sketch:
 *   (a) Serial injection for bench testing: send a line of
 *       NUM_RAW_FEATURES comma-separated floats over Serial.
 *   (b) REPLACE with your real flow-metering code (packet counters,
 *       inter-arrival times, byte counts, etc. computed over a sliding
 *       window) when wiring this to a live NIC/sniffer.
 */
bool getRawFeatureVector(float *raw) {
  if (Serial.available() > 0) {
    String line = Serial.readStringUntil('\n');
    line.trim();
    int idx = 0, start = 0;
    for (int i = 0; i <= line.length() && idx < NUM_RAW_FEATURES; i++) {
      if (i == line.length() || line[i] == ',') {
        raw[idx++] = line.substring(start, i).toFloat();
        start = i + 1;
      }
    }
    return idx == NUM_RAW_FEATURES;
  }
  return false;  // no new sample this cycle
}

/*
 * getSuspectedSrcIP()
 * ---------------------
 * The controller's mitigation engine needs to know WHICH source IP to
 * block. REPLACE this placeholder with the real source IP your
 * flow-metering routine extracted for the current window.
 */
String getSuspectedSrcIP() {
  return "10.0.0.5";  // <-- placeholder, wire to real flow metering
}

void sendAlert(int predictedClass) {
  if (WiFi.status() != WL_CONNECTED) {
    Serial.println("[Alert] WiFi not connected, cannot send alert.");
    return;
  }
  HTTPClient http;
  http.begin(CONTROLLER_URL);
  http.addHeader("Content-Type", "application/json");

  String payload = "{";
  payload += "\"device_id\":\"" + String(DEVICE_ID) + "\",";
  payload += "\"src_ip\":\"" + getSuspectedSrcIP() + "\",";
  payload += "\"predicted_class\":" + String(predictedClass) + ",";
  payload += "\"timestamp_ms\":" + String(millis());
  payload += "}";

  int httpCode = http.POST(payload);
  Serial.print("[Alert] POST -> "); Serial.print(CONTROLLER_URL);
  Serial.print(" | HTTP "); Serial.println(httpCode);
  if (httpCode > 0) Serial.println("[Alert] Response: " + http.getString());
  http.end();
}

void setup() {
  Serial.begin(115200);
  delay(1000);
  Serial.println("=== SD-IoT Edge Detection (ESP32, hardware mode) ===");
  Serial.print("Model expects "); Serial.print(NUM_RAW_FEATURES);
  Serial.println(" raw features, reduced internally to:");
  Serial.print("  "); Serial.print(NUM_PCA_COMPONENTS);
  Serial.println(" PCA components before the decision tree.");
  connectWiFi();
}

void loop() {
  if (millis() - lastSampleTime >= SAMPLE_INTERVAL_MS) {
    lastSampleTime = millis();

    float raw[NUM_RAW_FEATURES];
    if (getRawFeatureVector(raw)) {
      int predicted = classify_flow(raw);  // scaler -> PCA -> tree, all in generated_model.h

      Serial.print("[Predict] class=");
      Serial.println(predicted == 1 ? "ATTACK" : "BENIGN");

      if (predicted == 1) {
        sendAlert(predicted);
      }
    }
  }

  if (WiFi.status() != WL_CONNECTED) {
    connectWiFi();
  }
}
